name = "test-gateway"
main = "dist/index.mjs"
compatibility_date = "2023-01-01"
workers_dev = true

services = [
  { binding = "USER_SERVICE", service = "test-user" },
]

[build.upload]
format = "modules"

[miniflare]
route = "http://127.0.0.1:8787/*"